### ISSUE TITLE
WishlistPlugin: Can't add products to lists on update 2.0.0

### ISSUE THREAD

**Issue by ramon-sg** [vendure-ecommerce/vendure-plus-issues#24] opened 2023-07-06 17:45 UTC
This was working before the update to 2.0.0.

Basically when adding products to a list on a user we get the following error:

<img width="787" alt="Captura de pantalla 2023-07-06 a la(s) 13 42 52" src="https://github.com/vendure-ecommerce/vendure-plus-issues/assets/473091/168e1e7f-5ee2-429b-8464-5663a387ca2f">

![72a63f1f-fb1b-4a0e-bed2-62e119700f80](https://github.com/vendure-ecommerce/vendure-plus-issues/assets/473091/2779e25c-677d-44ab-9537-519bdbfea912)

**Comment by michaelbromley** [comment] 2023-07-26 06:52
Hi,

Thanks for your patience while I got around to this. Can you provide a bit more information on reproducing this:

- Is the customer logged in?
- Does the customer have a wishlist with the given id?

If you can provide a step-by-step reproduction, I will address this for a new patch release.

**Comment by michaelbromley** [comment] 2023-07-27 07:04
Hi Ricardo, thanks for the detailed instructions. I was not able to reproduce this, but I noticed that my version has some unpublished changes so I have just published a new version (v0.0.3) which I would like you to try, and let me know if it resolves the issue.

**Comment by rsat** [comment] 2023-07-27 13:01
Thanks Michael that sorted out the problem 👍

**Comment by michaelbromley** [comment] 2023-07-27 13:15
Great to hear! I'll close this issue then 👍

**Closed by michaelbromley** 2023-07-27 13:15 UTC
Labels: plugin: wishlist
